services:
    _defaults:
        autoconfigure: true
        autowire: true

    lemisoft.sylius_seo_integration_plugin.controller.shop.seo_integration_controller:
        class: Lemisoft\SyliusSeoIntegrationPlugin\Controller\Shop\SeoIntegrationController
        arguments:
            - '@lemisoft.sylius_seo_integration_plugin.service.seo_integration.seo_integration_service'
        tags:
            - { name: controller.service_arguments }
