services:
    lemisoft.sylius_seo_integration_plugin.registry.seo-integration-type:
        class: Sylius\Component\Registry\ServiceRegistry
        public: true
        arguments:
            - 'Lemisoft\SyliusSeoIntegrationPlugin\Service\SeoIntegration\Model\SeoIntegrationType\SeoIntegrationTypeInterface'
            - 'seo integration'
        calls:
            -   register: [ 'facebook', '@lemisoft.sylius_seo_integration_plugin.type.facebook' ]
            -   register: [ 'google_analytics', '@lemisoft.sylius_seo_integration_plugin.type.google_analytics' ]
            -   register: [ 'facebook_pixel', '@lemisoft.sylius_seo_integration_plugin.type.facebook_pixel' ]
            -   register: [ 'google_site_verification', '@lemisoft.sylius_seo_integration_plugin.type.google_site_verification' ]

    lemisoft.sylius_seo_integration_plugin.type.facebook:
        class: Lemisoft\SyliusSeoIntegrationPlugin\Service\SeoIntegration\Model\SeoIntegrationType\FacebookSeoIntegrationType

    lemisoft.sylius_seo_integration_plugin.type.google_analytics:
        class: Lemisoft\SyliusSeoIntegrationPlugin\Service\SeoIntegration\Model\SeoIntegrationType\GoogleAnalyticsSeoIntegrationType

    lemisoft.sylius_seo_integration_plugin.type.facebook_pixel:
        class: Lemisoft\SyliusSeoIntegrationPlugin\Service\SeoIntegration\Model\SeoIntegrationType\FacebookPixelSeoIntegrationType

    lemisoft.sylius_seo_integration_plugin.type.google_site_verification:
        class: Lemisoft\SyliusSeoIntegrationPlugin\Service\SeoIntegration\Model\SeoIntegrationType\GoogleSiteVerificationSeoIntegrationType
