sylius_grid:
    templates:
        action:
            create_seo_integration: "@LemisoftSyliusSeoIntegrationPlugin/Admin/SeoIntegration/Grid/Action/create.html.twig"
    grids:
        lemisoft_seo_integration_admin_seo_integration:
            driver:
                name: doctrine/orm
                options:
                    class: "%lemisoft_sylius_seo_integration_plugin.model.seo_integration.class%"
            sorting:
                name: asc
            fields:
                name:
                    type: string
                    label: sylius.ui.name
                type:
                    type: twig
                    label: sylius.ui.type
                    sortable: ~
                    options:
                        template: "@SyliusUi/Grid/Field/label.html.twig"
            filters:
                name:
                    type: string
                    label: sylius.ui.code
                type:
                    type: string
                    label: sylius.ui.type
            actions:
                main:
                    create:
                        type: create_seo_integration
                item:
                    update:
                        type: update
                    delete:
                        type: delete
                bulk:
                    delete:
                        type: delete
