name: e-commerce-boilerplate
services:
    app:
        image: sylius/standard:1.11-traditional
        environment:
            APP_ENV: "dev"
            DATABASE_URL: "mysql://sylius:${MYSQL_PASSWORD:-nopassword}@mysql/sylius?charset=utf8mb4"
            PHP_DATE_TIMEZONE: "Europe/Warsaw"
        volumes:
            - ./:/app:delegated
            - ./docker/php/php.ini:/etc/php8/php.ini:delegated
            - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:delegated
        ports:
            - 80:80
        depends_on:
            - mysql
        networks:
            - sylius

    mysql:
        image: mysql:8.0
        environment:
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-nopassword}
            - MYSQL_DATABASE=sylius
            - MYSQL_USER=sylius
            - MYSQL_PASSWORD=${MYSQL_PASSWORD:-nopassword}
        ports:
            - ${MYSQL_PORT:-3306}:3306
        networks:
            - sylius

networks:
    sylius:
        driver: bridge
