lemisoft_boilerplate_static_welcome:
    path: /static-welcome/{name}
    defaults:
        _controller: Lemisoft\BoilerplatePlugin\Controller\GreetingController::staticallyGreetAction
        name: ~

lemisoft_boilerplate_dynamic_welcome:
    path: /dynamic-welcome/{name}
    defaults:
        _controller: Lemisoft\BoilerplatePlugin\Controller\GreetingController::dynamicallyGreetAction
        name: ~
